name: Build and deploy WAR app to Azure Web App - amazon-gn

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17 (Microsoft distribution)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven (multi-module)
        run: mvn clean install -X  # -X for debug output if needed

      - name: Check if WAR file exists
        run: |
          echo "Looking for WAR in Amazon-Web/target/"
          ls -l Amazon-Web/target
          test -f Amazon-Web/target/*.war || (echo "WAR file not found!" && exit 1)

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: Amazon-Web/target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files (debugging)
        run: ls -l

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amjenkins'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: '*.war'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
