name: Build and Deploy WAR to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: List WAR files
        run: ls -lh Amazon-Web/target/*.war

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: amazon-war
          path: Amazon-Web/target/*.war

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amazon-gn'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Amazon-Web/target/Amazon.war
